USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR FINOPS_BUDGET_MONITOR
WITH
    CREDIT_QUOTA = 100,
    FREQUENCY = 'MONTHLY',
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

GRANT MONITOR ON RESOURCE MONITOR FINOPS_BUDGET_MONITOR TO ROLE CICD;

CREATE DATABASE IF NOT EXISTS {{ db }}
COMMENT = 'Development database for IOT domain - mother-of-all-Projects showcase';

CREATE SCHEMA IF NOT EXISTS {{ db }}.{{ schema }}
COMMENT = 'Raw data landing zone for IOT sensor data';

CREATE DCM PROJECT IF NOT EXISTS {{ db }}.{{ schema }}.MOTHER_OF_ALL_PROJECTS;
