USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR FINOPS_BUDGET_MONITOR
WITH
    CREDIT_QUOTA = 100,
    FREQUENCY = 'MONTHLY',
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

GRANT MONITOR ON RESOURCE MONITOR FINOPS_BUDGET_MONITOR TO ROLE CICD;
