-- RULE 8: Schema maturity prefix
CREATE SCHEMA IF NOT EXISTS RAW_test_v001;
CREATE SCHEMA IF NOT EXISTS CUR_test_v001;
CREATE SCHEMA IF NOT EXISTS test_no_prefix_v001;

-- RULE 9: Schema version suffix
CREATE SCHEMA IF NOT EXISTS RAW_sensors_v001;
CREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACREACage naming
CREATE OR REPLACE STAGE ICGI_RAW_ST_SWIFT_INBOUND FILE_FORMAT = (TYPE = XML);
CREATE OR REPLACE STAGE ICG_RAW_SWIFT_INBOUND FILE_FORMAT = (TYPE = XML);

-- RULE 26: File Format naming
CREATE OR REPLACE FILE FORMAT ICGI_RAW_FF_XML TYPE = XML;
CREATE OR REPLACE FILE FORMAT XML_FILE_FORMAT TYPE = XML;

-- RULE 27: Stored Procedure naming
CREATE OR REPLACE PROCEDURE IOTI_AGG_SP_CALCULATE_AVERAGES() RETURNS STRING LANGUAGE SQL AS 'SELECT 1';
CREATE OR REPLACE PROCEDURE CALC_AVERAGES() RETURNS STRING LANGUAGE SQL AS 'SELECT 1';

-- RULE 28: Task naming
CREATE OR REPLACE TASK IOTI_RAW_TK_INGEST_HOURLY WAREHOUSE = MD_TEST_WH SCHEDULE = 'USING CRON 0 * * * * UTC' AS SELECT 1;
CREATE OR REPLACE TASK HOURLY_INGEST WAREHOUSE = MD_TEST_WH SCHEDULE = 'USING CRON 0 * * * * UTC' AS SELECT 1;
