name: Update Local Repository and Run Sonar Scanner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pipeline:
    uses: zbrainiac-labs/DataOpsBackbone/.github/workflows/dataops-pipeline.yml@main
    with:
      SOURCE_DATABASE: DATAOPS
      SOURCE_SCHEMA: IOT_RAW_V001
      DCM_PROJECT_IDENTIFIER: DATAOPS.IOT_RAW_V001.MOTHER_OF_ALL_PROJECTS
      DCM_TARGET: DEV
    secrets: inherit
